---

dist: focal
sudo: true
language: sql

branches:
  only:
    - master

matrix:
  include:
    - addons:
        postgresql: 9.6
        apt:
          packages:
            - postgresql-server-dev-9.6
            - postgresql-9.6-pgtap
      env:
        - POSTGRESQL=9.6
    - addons:
        postgresql: 14.2
        apt:
          packages:
            - postgresql-server-dev-14.2
            - postgresql-14.2-pgtap
      env:
        - POSTGRESQL=14.2

script:
  - make
  - sudo make install
  - make test || cat regression.diffs


# vim: set ts=2 sts=2 sw=2 et:
